name: 签到

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    #格林尼治时间23：05，东八区北京时间7：05
    - cron: 05 23 * * *

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 签到
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
            
        - name: Install depends
          run: |
                sudo apt-get update
               
        - name: Run 号码1
          env:
           haoma: ${{ secrets.HAOMA }}
           mm: ${{ secrets.MM }}
           appid: ${{ secrets.APPID }}
          run: |
           bash CnUnicom.sh ${haoma} ${mm} ${appid}
           
